apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-deleted.slack: {{ include "commondev.getTagURLforNotificationChannel" (dict "tag" .Values.release.tag "url" .Values.release.url) }}
		customtag: {{ .Values.commondev.slack_notification_channel }}

spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
